import type { Court } from "@/lib/types";

export const NYC_PARKS_PICKLEBALL_URL =
  "https://www2.nycgovparks.org/facilities/pickleball";
export const NYC_PICKLEBALL_GUIDE_URL = "https://www.nycpickleball.com/the-guide";

export const courts: Court[] = [
  {
    id: "crotona-park",
    slug: "crotona-park",
    name: "Crotona Park",
    borough: "Bronx",
    parkName: "Crotona Park",
    location: "Crotona Park North to South, Fulton Ave to Southern Blvd and Crotona Park East",
    latitude: 40.8394,
    longitude: -73.8958,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "pelham-bay-park",
    slug: "pelham-bay-park",
    name: "Pelham Bay Park",
    borough: "Bronx",
    parkName: "Pelham Bay Park",
    location: "Orchard Beach, on Long Island Sound in Pelham Bay Park",
    latitude: 40.8676,
    longitude: -73.7959,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "riverdale-playground",
    slug: "riverdale-playground",
    name: "Riverdale Playground",
    borough: "Bronx",
    parkName: "Riverdale Playground",
    location: "Hudson Manor Ter between W 237 St and W 236 St",
    latitude: 40.8875,
    longitude: -73.9163,
    courtCount: 1,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "van-cortlandt-park",
    slug: "van-cortlandt-park",
    name: "Van Cortlandt Park",
    borough: "Bronx",
    parkName: "Van Cortlandt Park",
    location: "Van Cortlandt Park S between John M. Collins Pl and Putnam Ave W",
    latitude: 40.8872,
    longitude: -73.8848,
    courtCount: 1,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "williamsbridge-oval",
    slug: "williamsbridge-oval",
    name: "Williamsbridge Oval",
    borough: "Bronx",
    parkName: "Williamsbridge Oval",
    location: "Van Cortlandt Ave East, Reservoir Oval E",
    latitude: 40.8778,
    longitude: -73.8775,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "breukelen-ballfields",
    slug: "breukelen-ballfields",
    name: "Breukelen Ballfields",
    borough: "Brooklyn",
    parkName: "Breukelen Ballfields",
    location: "Louisiana Ave and Stanley Ave",
    latitude: 40.651,
    longitude: -73.8926,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "john-j-carty-park",
    slug: "john-j-carty-park",
    name: "John J Carty Park",
    borough: "Brooklyn",
    parkName: "John J Carty Park",
    location: "Fort Hamilton Pkwy between 99th and 100th Sts",
    latitude: 40.6121,
    longitude: -74.0345,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "leif-ericson-park",
    slug: "leif-ericson-park",
    name: "Leif Ericson Park",
    borough: "Brooklyn",
    parkName: "Leif Ericson Park",
    location: "8th Avenue between 66th and 67th Sts",
    latitude: 40.6348,
    longitude: -74.0112,
    courtCount: 13,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "linden-park",
    slug: "linden-park",
    name: "Linden Park",
    borough: "Brooklyn",
    parkName: "Linden Park",
    location: "Vermont St between Linden Blvd and Stanley Ave",
    latitude: 40.6561,
    longitude: -73.8899,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "winthrop-playground",
    slug: "winthrop-playground",
    name: "Winthrop Playground",
    borough: "Brooklyn",
    parkName: "Winthrop Playground",
    location: "Winthrop St between Bedford Ave and Rogers Ave",
    latitude: 40.6575,
    longitude: -73.9533,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "carl-schurz-park",
    slug: "carl-schurz-park",
    name: "Carl Schurz Park",
    borough: "Manhattan",
    parkName: "Carl Schurz Park",
    location: "East End Ave to East River, E 84 St to E 90 St",
    latitude: 40.7751,
    longitude: -73.9437,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "james-j-walker-park",
    slug: "james-j-walker-park",
    name: "James J Walker Park",
    borough: "Manhattan",
    parkName: "James J Walker Park",
    location: "Hudson St, St. Luke's Pl, Clarkson St, 7 Ave",
    latitude: 40.7307,
    longitude: -74.0061,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "alley-athletic-playground",
    slug: "alley-athletic-playground",
    name: "Alley Athletic Playground",
    borough: "Queens",
    parkName: "Alley Athletic Playground",
    location: "79-20 Winchester Avenue",
    latitude: 40.7415,
    longitude: -73.7339,
    courtCount: 4,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "crocheron-park",
    slug: "crocheron-park",
    name: "Crocheron Park",
    borough: "Queens",
    parkName: "Crocheron Park",
    location: "214 Pl, 214 La, 215 Pl, Cross Island Pkwy between 33 Ave and 35 Ave",
    latitude: 40.7716,
    longitude: -73.7662,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "farm-playground",
    slug: "farm-playground",
    name: "Farm Playground",
    borough: "Queens",
    parkName: "Farm Playground",
    location: "73rd Ave between 196th Pl and 196th St",
    latitude: 40.7337,
    longitude: -73.7794,
    courtCount: 1,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "francis-lewis-park",
    slug: "francis-lewis-park",
    name: "Francis Lewis Park",
    borough: "Queens",
    parkName: "Francis Lewis Park",
    location: "3rd Avenue beneath Whitestone Expwy",
    latitude: 40.7942,
    longitude: -73.8243,
    courtCount: 1,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "louis-pasteur-park",
    slug: "louis-pasteur-park",
    name: "Louis Pasteur Park",
    borough: "Queens",
    parkName: "Louis Pasteur Park",
    location: "248th St at 52nd Ave",
    latitude: 40.7611,
    longitude: -73.7349,
    courtCount: 2,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "rockaway-beach-boardwalk",
    slug: "rockaway-beach-boardwalk",
    name: "Rockaway Beach And Boardwalk",
    borough: "Queens",
    parkName: "Rockaway Beach And Boardwalk",
    location: "Shore Front Parkway and Beach 102nd Street",
    latitude: 40.583,
    longitude: -73.8204,
    courtCount: 1,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "roy-wilkins-recreation-center",
    slug: "roy-wilkins-recreation-center",
    name: "Roy Wilkins Recreation Center",
    borough: "Queens",
    parkName: "Roy Wilkins Recreation Center",
    location: "Baisley Blvd between 177th St and 120th Ave",
    latitude: 40.6878,
    longitude: -73.7718,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "fairview-park",
    slug: "fairview-park",
    name: "Fairview Park",
    borough: "Staten Island",
    parkName: "Fairview Park",
    location: "Enter at parking lot on Bricktown Way and Tyrellan Ave",
    latitude: 40.5285,
    longitude: -74.2302,
    courtCount: 3,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "skyline-playground",
    slug: "skyline-playground",
    name: "Skyline Playground",
    borough: "Staten Island",
    parkName: "Skyline Playground",
    location: "Arnold St to Prospect Ave between Harvard Ave and Clyde Pl",
    latitude: 40.6176,
    longitude: -74.0872,
    courtCount: 4,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PARKS_PICKLEBALL_URL,
  },
  {
    id: "central-park-north-meadow",
    slug: "central-park-north-meadow",
    name: "Central Park North Meadow",
    borough: "Manhattan",
    parkName: "Central Park",
    location: "Mid-park around 97th St, North Meadow handball courts",
    latitude: 40.7901,
    longitude: -73.9584,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
    notes: "Community guide listing; verify current striping and court availability.",
  },
  {
    id: "de-witt-clinton-park",
    slug: "de-witt-clinton-park",
    name: "DeWitt Clinton Park",
    borough: "Manhattan",
    parkName: "DeWitt Clinton Park",
    location: "11th Ave and W 52nd St",
    latitude: 40.7685,
    longitude: -73.9936,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "happy-warrior-playground",
    slug: "happy-warrior-playground",
    name: "Happy Warrior Playground",
    borough: "Manhattan",
    parkName: "Happy Warrior Playground",
    location: "Amsterdam Ave between W 98th St and W 99th St",
    latitude: 40.7958,
    longitude: -73.9693,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "hudson-river-park-pier-76",
    slug: "hudson-river-park-pier-76",
    name: "Hudson River Park Pier 76",
    borough: "Manhattan",
    parkName: "Hudson River Park",
    location: "12th Ave and W 34th St",
    latitude: 40.7592,
    longitude: -74.0028,
    courtCount: 4,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "lillian-d-wald-playground",
    slug: "lillian-d-wald-playground",
    name: "Lillian D Wald Playground",
    borough: "Manhattan",
    parkName: "Lillian D Wald Playground",
    location: "Cherry St and Gouverneur St",
    latitude: 40.7102,
    longitude: -73.9894,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "roosevelt-island-sportspark",
    slug: "roosevelt-island-sportspark",
    name: "Roosevelt Island Sportspark",
    borough: "Manhattan",
    parkName: "Roosevelt Island Sportspark",
    location: "250 Main St, Roosevelt Island",
    latitude: 40.7617,
    longitude: -73.949,
    courtCount: 4,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
    notes: "Community guide listing; access details may differ from NYC Parks outdoor courts.",
  },
  {
    id: "sol-lain-playground",
    slug: "sol-lain-playground",
    name: "Sol Lain Playground",
    borough: "Manhattan",
    parkName: "Sol Lain Playground",
    location: "E Broadway and Henry St",
    latitude: 40.7141,
    longitude: -73.9847,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "st-catherines-park",
    slug: "st-catherines-park",
    name: "St Catherine's Park",
    borough: "Manhattan",
    parkName: "St Catherine's Park",
    location: "1st Ave between E 67th St and E 68th St",
    latitude: 40.7653,
    longitude: -73.9585,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "st-vartan-park",
    slug: "st-vartan-park",
    name: "St Vartan Park",
    borough: "Manhattan",
    parkName: "St Vartan Park",
    location: "1st Ave and E 35th St",
    latitude: 40.7456,
    longitude: -73.9734,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "william-f-passannante-ballfield",
    slug: "william-f-passannante-ballfield",
    name: "William F Passannante Ballfield",
    borough: "Manhattan",
    parkName: "William F Passannante Ballfield",
    location: "W Houston St and 6th Ave",
    latitude: 40.7285,
    longitude: -74.004,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "city-pickle-wollman-rink",
    slug: "city-pickle-wollman-rink",
    name: "CityPickle at Wollman Rink",
    borough: "Manhattan",
    parkName: "Wollman Rink",
    location: "Central Park near E 59th St and 6th Ave",
    latitude: 40.7677,
    longitude: -73.9748,
    courtCount: 14,
    permitRequired: true,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
    notes: "Seasonal/paid community guide listing.",
  },
  {
    id: "brooklyn-bridge-park-pier-2",
    slug: "brooklyn-bridge-park-pier-2",
    name: "Brooklyn Bridge Park Pier 2",
    borough: "Brooklyn",
    parkName: "Brooklyn Bridge Park",
    location: "Pier 2, Brooklyn Bridge Park",
    latitude: 40.6995,
    longitude: -73.9994,
    courtCount: 3,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "di-mattina-playground",
    slug: "di-mattina-playground",
    name: "DiMattina Playground",
    borough: "Brooklyn",
    parkName: "DiMattina Playground",
    location: "Rapelye St and Hicks St",
    latitude: 40.6805,
    longitude: -74.0041,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "marine-park-pickleball-courts",
    slug: "marine-park-pickleball-courts",
    name: "Marine Park Pickleball Courts",
    borough: "Brooklyn",
    parkName: "Marine Park",
    location: "Fillmore Ave and Marine Pkwy",
    latitude: 40.6089,
    longitude: -73.9328,
    courtCount: 8,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "mccarren-park",
    slug: "mccarren-park",
    name: "McCarren Park",
    borough: "Brooklyn",
    parkName: "McCarren Park",
    location: "Bedford Ave and N 12th St",
    latitude: 40.7216,
    longitude: -73.9517,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "squibb-park",
    slug: "squibb-park",
    name: "Squibb Park",
    borough: "Brooklyn",
    parkName: "Squibb Park",
    location: "Columbia Heights and Middagh St",
    latitude: 40.7003,
    longitude: -73.9957,
    courtCount: 3,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "astoria-park",
    slug: "astoria-park",
    name: "Astoria Park",
    borough: "Queens",
    parkName: "Astoria Park",
    location: "19th St and Hoyt Ave N",
    latitude: 40.7795,
    longitude: -73.9229,
    courtCount: 3,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "flushing-meadows-corona-park",
    slug: "flushing-meadows-corona-park",
    name: "Flushing Meadows Corona Park",
    borough: "Queens",
    parkName: "Flushing Meadows Corona Park",
    location: "USTA National Tennis Center area",
    latitude: 40.7498,
    longitude: -73.8469,
    courtCount: 4,
    permitRequired: true,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "hunterspoint-south-park",
    slug: "hunterspoint-south-park",
    name: "Hunter's Point South Park",
    borough: "Queens",
    parkName: "Hunter's Point South Park",
    location: "Center Blvd and 51st Ave",
    latitude: 40.7428,
    longitude: -73.9599,
    courtCount: 3,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "juniper-valley-park",
    slug: "juniper-valley-park",
    name: "Juniper Valley Park",
    borough: "Queens",
    parkName: "Juniper Valley Park",
    location: "Juniper Blvd N and 80th St",
    latitude: 40.7216,
    longitude: -73.8812,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "macneil-park",
    slug: "macneil-park",
    name: "MacNeil Park",
    borough: "Queens",
    parkName: "MacNeil Park",
    location: "Poppenhusen Ave and 119th St",
    latitude: 40.7935,
    longitude: -73.8499,
    courtCount: 2,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "riverside-park-staten-island",
    slug: "riverside-park-staten-island",
    name: "Riverside Park",
    borough: "Staten Island",
    parkName: "Riverside Park",
    location: "Schmidts Lane and Manor Rd",
    latitude: 40.6088,
    longitude: -74.1205,
    courtCount: 4,
    permitRequired: false,
    accessible: false,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
  {
    id: "willowbrook-park",
    slug: "willowbrook-park",
    name: "Willowbrook Park",
    borough: "Staten Island",
    parkName: "Willowbrook Park",
    location: "Eton Pl and Richmond Ave",
    latitude: 40.6034,
    longitude: -74.1588,
    courtCount: 4,
    permitRequired: false,
    accessible: true,
    active: true,
    sourceUrl: NYC_PICKLEBALL_GUIDE_URL,
  },
];

export function getCourtBySlug(slug: string) {
  return courts.find((court) => court.slug === slug);
}

export function getCourtById(id: string) {
  return courts.find((court) => court.id === id);
}
